export { HomeComponent, DialogAsk } from './home/home.component';
export { AboutComponent } from './about/about.component';
export { GetingstartedComponent } from './getingstarted/getingstarted.component';
export { SignupComponent } from './signup/signup.component';
export { NotfoundComponent } from './notfound/notfound.component';
export { ListComponent } from './list/list.component';
export { ProfileComponent } from './profile/profile.component';
export { EdituserComponent } from './profile/edituser/edituser.component';
export { AddComponent, BlogComponent } from './add/add.component';
export { PageComponent } from './page/page.component';